# Generated by Django 5.1.2 on 2024-11-03 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[(1, 'Not Started'), (2, 'WIP'), (3, 'Finished')], max_length=20)),
                ('Priority', models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], max_length=20)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
