# Generated by Django 5.1.2 on 2024-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('todo', 'To Do'), ('pending', 'Pending'), ('finished', 'Finished')], max_length=20),
        ),
    ]
